### ISSUE TITLE
apcu support

### ISSUE THREAD

**Issue by lalop** [pix-art/LexikTranslationSonataBundle#2]
I tried your plugin with php 7 and I get this error

```
Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "apc_exists" from namespace "Lexik\Bundle\TranslationBundle\Translation"
```

I have apcu installed not apc, is there a way to make it work ?

**Comment by lalop** [comment]
related to lexik bundle https://github.com/lexik/LexikTranslationBundle/issues/237

**Comment by pix-art** [comment]
Ah thanks for figuring that out :-) I'm sure as soon as they fix that we should be good aswell!
